name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-values:
    runs-on: ubuntu-latest

    env:
      NAMESPACE: "starship"

    steps:

      - uses: actions/checkout@v2

      - uses: ./
        with:
          port-forward: true
          name: test-with-values
          values: |
            chains:
            - name: osmosis-1
              type: osmosis
              numValidators: 1
              ports:
                rest: 1313
                rpc: 26653
              resources:
                limits:
                  cpu: "0.2"
                  memory: "200M"
                requests:
                  cpu: "0.1"
                  memory: "100M"
            - name: wasmd
              type: wasmd
              numValidators: 1
              ports:
                rpc: 26659
                rest: 1319
              resources:
                limits:
                  cpu: "0.2"
                  memory: "200M"
                requests:
                  cpu: "0.1"
                  memory: "100M"

      - name: Check kubectl pods
        run: |
          echo "namespace here.... $NAMESPACE and also ${{ env.NAMESPACE }}"
          echo testing $NAMESPACE
          for chain in wasmd osmosis-1; do
            kubectl get pods $chain-genesis-0 --namespace $NAMESPACE
          done

      - name: Check port forwarded status
        run: |
          for port in 26659 26653; do
            status_code=$(curl --write-out %{http_code} --silent --output /dev/null http://localhost:$port/status)
            if [[ "$status_code" -ne 200 ]]; then
              echo "Expected status code: 200, got: $status_code, from http://localhost:$port/status"
              exit 1
            else
              echo "Successfully connected to: http://localhost:$port/status"
            fi
          done

      - name: Delete helm chart
        run: |
          helm delete test-with-values --debug --namespace ${{ env.NAMESPACE }}

  test-with-remote-cluster:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - run: echo -e "$TEMP_KUBECONFIG" > /tmp/kubeconfig
        shell: bash
        env:
          TEMP_KUBECONFIG: |
            apiVersion: v1
            kind: Config
            preferences: {}

      - name: Setup kind cluster
        if: ${{ inputs.kubeconfig == '' }}
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind-starship
        env:
          KUBECONFIG: /tmp/kubeconfig

      - name: Read kubeconfig
        id: kubeconfig
        uses: juliangruber/read-file-action@v1
        with:
          path: /tmp/kubeconfig

      - uses: ./
        with:
          port-forward: true
          name: test-kubeconfig
          kubeconfig: ${{ steps.kubeconfig.outputs.content }}
          values: |
            chains:
            - name: osmosis-1
              type: osmosis
              numValidators: 1
              ports:
                rest: 1313
                rpc: 26653
              resources:
                limits:
                  cpu: "0.2"
                  memory: "200M"
                requests:
                  cpu: "0.1"
                  memory: "100M"

      - name: Check kubectl pods
        run: |
          echo "namespace here.... $NAMESPACE and also ${{ env.NAMESPACE }}"
          echo testing $NAMESPACE
          kubectl get pods osmosis-1-genesis-0 --namespace ${{ env.NAMESPACE }}

      - name: Delete helm chart
        run: |
          helm delete test-kubeconfig --debug --namespace ${{ env.NAMESPACE }}

  test-with-no-portforward:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: ./
        with:
          port-forward: false
          name: test-no-portforward
          values: |
            chains:
            - name: osmosis-1
              type: osmosis
              numValidators: 1
              resources:
                limits:
                  cpu: "0.2"
                  memory: "200M"
                requests:
                  cpu: "0.1"
                  memory: "100M"

      - name: Check kubectl pods
        run: |
          echo "namespace here.... $NAMESPACE and also ${{ env.NAMESPACE }}"
          echo testing $NAMESPACE
          for chain in osmosis-1; do
            kubectl get pods $chain-genesis-0 --namespace ${{ env.NAMESPACE }}
          done

      - name: Delete helm chart
        run: |
          helm delete test-no-portforward --debug --namespace ${{ env.NAMESPACE }}
